language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - nightly

before_script:
    - composer self-update
    - composer install --dev
    - mkdir -p build/logs

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
